apiVersion: v1
kind: Service
metadata:
  name: engagement-tracker-service
  labels:
    app: engagement-tracker
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: engagement-tracker