apiVersion: v1
kind: Namespace
metadata:
  name: turbo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: turbo-user
  namespace: turbo
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1    
metadata:
  name: turbo-all-binding
  namespace: turbo
subjects:
- kind: ServiceAccount
  name: turbo-user
  namespace: turbo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  # use this yaml to create a config that kubeturbo will use to connect to the Turbo Server
  # requires Turbo Server and kubeturbo pod 6.4.3 and higher 
  # Provide a value for the config name: and update namespace if needed
  name: turbo-config
  namespace: turbo
data:
  # Update the values for version, turboServer, opsManagerUserName, opsManagerPassword
  # For version, use Turbo Server Version, even when running CWOM
  # The opsManagerUserName requires Turbo administrator role
  #
  # For targetConfig, targetName provides better group naming to identify k8s clusters in UI
  # - If no targetConfig is specified, a default targetName will be created from the apiserver URL in
  #   the kubeconfig.
  # - Specify a targetName only will register a probe with type Kubernetes-<targetName>, as well as
  #   adding your cluster as a target with the name Kubernetes-<targetName>.
  # - Specify a targetType only will register a probe without adding your cluster as a target.
  #   The probe will appear as a Cloud Native probe in the UI with a type Kubernetes-<targetType>.
  #
  # Define node groups by node role, and automatically enable placement policies to limit to 1 per host
  # DaemonSets are identified by default. Use daemonPodDetectors to identify by name patterns using regex or by namespace.
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "8.3",
                "turboServer": "https://topology-processor-turbo.turbo-2bd2c162965d593cc66365794b1d3a7f-0000.us-south.containers.appdomain.cloud"
            },
            "restAPIConfig": {
                "opsManagerUserName": "Administrator",
                "opsManagerPassword": "turbo4test"
            }
        },
        "targetConfig": {
            "targetName": "kubezone"
        },
        "HANodeConfig": {
            "nodeRoles": [ "master" ]
        }
    }