apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
spec:
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-volume
  volumeMode: Filesystem